### ISSUE TITLE
ValueError: need at least one array to concatenate

### ISSUE THREAD

**Issue by LKXHZD** [icey-zhang/E2E-MFD#9]

**Comment by LKXHZD** [comment]
I meet this problem,please help me.

**Comment by LKXHZD** [comment]
您好，应该不是这个问题，我设置的路径后是有斜杆的。您能给我训练过程中dronevehicle_m.py文件的train、val、text对应的是数据集中的哪些文件吗？那个数据集下的图像和标签我不知道训练过程使用哪一个（例如：ir还是rgb，用的标签是ir的还是rgb的标签）。非常感谢。

**Comment by StarBlue98** [comment]
> 参考此博客，可能是数据集路径问题https://blog.csdn.net/yinxionge5233/article/details/127943250

哈喽，我也报了这个错误。我查看了自己的训练的log，和您公布的train.log去对比了一下，发现有这个问题，确实是数据集路径问题。
<img width="631" alt="SCR-20241024-qgcs" src="https://github.com/user-attachments/assets/35639c26-772d-44a4-9643-b346bfb76a84">
想问问这个。annfile 和 image 的设置路径是应该怎么去修改才对呢？我不是很明白

**Comment by LKXHZD** [comment]
会不会是因为没有checkpoint='/home/***/LSK***/lsk_s_backbone.pth.tar'这个文件报的错呢？看了很多博客都没解决，求助，非常感谢！

**Comment by kaka-Cao** [comment]
数据集的格式如这里所示https://github.com/icey-zhang/E2E-MFD?tab=readme-ov-file#prepare-the-dataset-dronevehicle，在dronevehicle_m.py配置文件中，ann_file应该设置为IR图像对应标签的地址，因为IR图像对应的标签是全部目标的；img_prefix应该设置为RGB图像的地址，只用给RGB图像的地址是因为他会自动替换路径中的rgb去找到ir下的图片。以上设置均适用于train,val,test数据集路径设置

**Comment by kaka-Cao** [comment]
> 会不会是因为没有checkpoint='/home/_**/LSK**_/lsk_s_backbone.pth.tar'这个文件报的错呢？看了很多博客都没解决，求助，非常感谢！

是的，您需要在lsk_s_fpn_1x_dota_le90.py文件中model.backbone.init_cfg这里传入预训练权重的路径，例如init_cfg=dict(type='Pretrained', checkpoint="/home/.../lsk_s_backbone.pth.tar")

**Comment by kaka-Cao** [comment]
数据集的格式如这里所示https://github.com/icey-zhang/E2E-MFD?tab=readme-ov-file#prepare-the-dataset-dronevehicle，在dronevehicle_m.py配置文件中，ann_file应该设置为IR图像对应标签的地址，因为IR图像对应的标签是全部目标的；img_prefix应该设置为RGB图像的地址，只用给RGB图像的地址是因为他会自动替换路径中的rgb去找到ir下的图片。以上设置均适用于train,val,test数据集路径设置

**Comment by kaka-Cao** [comment]
数据集的格式如这里所示[](https://github.com/icey-zhang/E2E-MFD?tab=readme-ov-file#prepare-the-dataset-dronevehicle)，在dronevehicle_m.py配置文件中，ann_file应该设置为IR图像对应标签的地址，因为IR图像对应的标签是全部目标的；img_prefix应该设置为RGB图像的地址，只用给RGB图像的地址是因为他会自动替换路径中的rgb去找到ir下的图片。以上设置均适用于train,val,test数据集路径设置。

**Comment by kaka-Cao** [comment]
[https://github.com/icey-zhang/E2E-MFD?tab=readme-ov-file#prepare-the-dataset-dronevehicle]数据集的格式如这里所示，在dronevehicle_m.py配置文件中，ann_file应该设置为IR图像对应标签的地址，因为IR图像对应的标签是全部目标的；img_prefix应该设置为RGB图像的地址，只用给RGB图像的地址是因为他会自动替换路径中的rgb去找到ir下的图片。以上设置均适用于train,val,test数据集路径设置

**Comment by StarBlue98** [comment]
嗨喽，感谢您的回复！
是否可以理解为数据集的配置，标签就只使用了ir的label，不会使用rgb的label。图片虽然写的是rgb，是在训练过程中也会对应的使用到ir的图像？

看到论文中，在训练过程是只用了train set，并没有使用 val set。想请问如果在训练过程中使用trainval 
 set去做训练，这样的效果是会更差吗？

以及现在的配置是使用单卡训练，您有试过多卡训练的一些相关配置参数吗？多卡训练时会什么配置参数比较好呢？

我想问一下论文是否有做一些公开的演讲或者是论文解读呢？
万分感谢！

**Comment by StarBlue98** [comment]
哈喽，我刚才根据您的建议去修改了tools/cfg/dronevehicle_m.py下的路径 ，但依旧还会报错。
<img width="290" alt="SCR-20241024-sffb" src="https://github.com/user-attachments/assets/017ed006-13a3-467a-9c58-18ad33765e42">
<img width="893" alt="SCR-20241024-sght" src="https://github.com/user-attachments/assets/15107611-918e-45ba-a53e-7ad81e6e6108">

我在想是不是我在安装过程中对mmdet mmcv. mmrotate的安装可能有问题？我看到您在git中也提供了mmdet  mmcv. mmrotate的相关文件夹，想问问是如何使用的呢

**Comment by LKXHZD** [comment]
> > 会不会是因为没有checkpoint='/home/_**/LSK**_/lsk_s_backbone.pth.tar'这个文件报的错呢？看了很多博客都没解决，求助，非常感谢！
> 
> 是的，您需要在lsk_s_fpn_1x_dota_le90.py文件中model.backbone.init_cfg这里传入预训练权重的路径，例如init_cfg=dict(type='Pretrained', checkpoint="/home/.../lsk_s_backbone.pth.tar")

我想问一下，lsk_s_backbone.pth.tar这个预训练文件怎么获得？是要找到其中epoch与自己训练时相同的才行吗？谢谢。

**Comment by StarBlue98** [comment]
> > > 会不会是因为没有checkpoint='/home/_**/LSK**_/lsk_s_backbone.pth.tar'这个文件报的错呢？看了很多博客都没解决，求助，非常感谢！
> > 
> > 
> > 是的，您需要在lsk_s_fpn_1x_dota_le90.py文件中model.backbone.init_cfg这里传入预训练权重的路径，例如init_cfg=dict(type='Pretrained', checkpoint="/home/.../lsk_s_backbone.pth.tar")
> 
> 我想问一下，lsk_s_backbone.pth.tar这个预训练文件怎么获得？是要找到其中epoch与自己训练时相同的才行吗？谢谢。

你可以从这个链接中下载：https://github.com/zcablii/LSKNet
但是我已经在config中加载了权重文件，依然还会报这个错误

**Comment by LKXHZD** [comment]
> 你可以从这个链接中下载：https://github.com/zcablii/LSKNet 但是我已经在config中加载了权重文件，依然还会报这个错误

感谢，那应该下载里面的哪一个呢？

**Comment by LKXHZD** [comment]
> 嗨喽，感谢您的回复！ 是否可以理解为数据集的配置，标签就只使用了ir的label，不会使用rgb的label。图片虽然写的是rgb，是在训练过程中也会对应的使用到ir的图像？
> 
> 看到论文中，在训练过程是只用了train set，并没有使用 val set。想请问如果在训练过程中使用trainval set去做训练，这样的效果是会更差吗？
> 
> 以及现在的配置是使用单卡训练，您有试过多卡训练的一些相关配置参数吗？多卡训练时会什么配置参数比较好呢？
> 
> 我想问一下论文是否有做一些公开的演讲或者是论文解读呢？ 万分感谢！

我想问一下单卡训练时，单卡的显存最低要求是多少才能运行啊？

**Comment by Wzlzh123** [comment]
> > > > 会不会是因为没有checkpoint='/home/_**/LSK**_/lsk_s_backbone.pth.tar'这个文件报的错呢？看了很多博客都没解决，求助，非常感谢！
> > > 
> > > 
> > > 是的，您需要在lsk_s_fpn_1x_dota_le90.py文件中model.backbone.init_cfg这里传入预训练权重的路径，例如init_cfg=dict(type='Pretrained', checkpoint="/home/.../lsk_s_backbone.pth.tar")
> > 
> > 
> > 我想问一下，lsk_s_backbone.pth.tar这个预训练文件怎么获得？是要找到其中epoch与自己训练时相同的才行吗？谢谢。
> 
> 你可以从这个链接中下载：https://github.com/zcablii/LSKNet 但是我已经在config中加载了权重文件，依然还会报这个错误

数据集得是DOTA格式

**Comment by wisdomwxy** [comment]
请问一下，我的数据集格式为
./train/trainimg
./train/trainlabelr
./train/trainimgr
./train/trainlabel
./train
./test/testlabelr
./test/testimg
./test/testimgr
./test/testlabel
./test
这是根据作者提供的链接下载的，是否需要转化成DOTA格式？
权重文件是sk_t_fpn_1x_dota_le90_20230206-3ccee254.pth
感激不尽！

**Comment by LKXHZD** [comment]
我也想问怎么把数据转化为DOTA格式啊？仍旧报错：ValueError: need at least one array to concatenate

**Comment by Wzlzh123** [comment]
https://github.com/icey-zhang/E2E-MFD/issues/12#issuecomment-2527283160     You can try labeling my training set. I hope it can solve your problem.

**Comment by UnchangedOriInten** [comment]
> [#12 (comment)](https://github.com/icey-zhang/E2E-MFD/issues/12#issuecomment-2527283160) You can try labeling my training set. I hope it can solve your problem.

I try your training set,then I meet another error:

Traceback (most recent call last):
  File "/opt/conda/envs/E2E-MFD/lib/python3.9/site-packages/mmcv/utils/registry.py", line 69, in build_from_cfg
    return obj_cls(**args)
  File "/root/E2E-MFD/mmrotate/datasets/dronevehicle.py", line 46, in __init__
    super(DroneVehicleDataset, self).__init__(ann_file, pipeline, **kwargs)
  File "/opt/conda/envs/E2E-MFD/lib/python3.9/site-packages/mmdet/datasets/custom.py", line 97, in __init__
    self.data_infos = self.load_annotations(local_path)
  File "/root/E2E-MFD/mmrotate/datasets/dronevehicle.py", line 100, in load_annotations
    difficulty = int(bbox_info[9])
ValueError: invalid literal for int() with base 10: 'car'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/E2E-MFD/./tools/train.py", line 193, in <module>
    main()
  File "/root/E2E-MFD/./tools/train.py", line 169, in main
    datasets = [build_dataset(cfg.data.train)]
  File "/root/E2E-MFD/mmrotate/datasets/builder.py", line 47, in build_dataset
    dataset = build_from_cfg(cfg, ROTATED_DATASETS, default_args)
  File "/opt/conda/envs/E2E-MFD/lib/python3.9/site-packages/mmcv/utils/registry.py", line 72, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
ValueError: DroneVehicleDataset: invalid literal for int() with base 10: 'car'
how can i solve it?

**Comment by IVEN-CN** [comment]
在文件`./mmrotate/datasets/dronevehicle.py`中，我注意到`DroneVehicleDataset.load_annotations`函数似乎没有读取xml格式的labels，我修改了这个函数，似乎解决了这个问题

```python
def load_annotations(self, ann_folder):
        """
            Args:
                ann_folder: folder that contains DOTA v1 annotations xml files
        """
        cls_map = {c: i for i, c in enumerate(self.CLASSES)}  # in mmdet v2.0 label is 0-based
        ann_files = glob.glob(ann_folder + '/*.xml')
        data_infos = []

        for ann_file in ann_files:
            data_info = {}
            img_id = osp.split(ann_file)[1][:-4]
            img_name = img_id + '.jpg'
            data_info['filename'] = img_name
            data_info['ann'] = {}
            gt_bboxes = []
            gt_labels = []
            gt_polygons = []
            gt_bboxes_ignore = []
            gt_labels_ignore = []
            gt_polygons_ignore = []

            tree = ET.parse(ann_file)
            root = tree.getroot()

            for obj in root.findall('object'):
                if obj is None:
                    continue
                cls_name = obj.find('name').text
                if cls_name == "feright car" or cls_name == "feright":
                    cls_name = "feright_car"
                if cls_name not in cls_map:
                    continue
                label = cls_map[cls_name]
                polygon = obj.find('polygon')
                if polygon is None:
                    continue
                x1 = float(polygon.find('x1').text)
                y1 = float(polygon.find('y1').text)
                x2 = float(polygon.find('x2').text)
                y2 = float(polygon.find('y2').text)
                x3 = float(polygon.find('x3').text)
                y3 = float(polygon.find('y3').text)
                x4 = float(polygon.find('x4').text)
                y4 = float(polygon.find('y4').text)
                poly = np.array([x1, y1, x2, y2, x3, y3, x4, y4], dtype=np.float32)
                try:
                    x, y, w, h, a = poly2obb_np(poly, self.version)
                except:  # noqa: E722
                    continue
                diff = obj.find('difficult')
                if diff is None:
                    continue
                difficulty = int(diff.text)
                if difficulty > self.difficulty:
                    pass
                else:
                    gt_bboxes.append([x, y, w, h, a])
                    gt_labels.append(label)
                    gt_polygons.append(poly)

            if gt_bboxes:
                data_info['ann']['bboxes'] = np.array(gt_bboxes, dtype=np.float32)
                data_info['ann']['labels'] = np.array(gt_labels, dtype=np.int64)
                data_info['ann']['polygons'] = np.array(gt_polygons, dtype=np.float32)
            else:
                data_info['ann']['bboxes'] = np.zeros((0, 5), dtype=np.float32)
                data_info['ann']['labels'] = np.array([], dtype=np.int64)
                data_info['ann']['polygons'] = np.zeros((0, 8), dtype=np.float32)

            if gt_polygons_ignore:
                data_info['ann']['bboxes_ignore'] = np.array(gt_bboxes_ignore, dtype=np.float32)
                data_info['ann']['labels_ignore'] = np.array(gt_labels_ignore, dtype=np.int64)
                data_info['ann']['polygons_ignore'] = np.array(gt_polygons_ignore, dtype=np.float32)
            else:
                data_info['ann']['bboxes_ignore'] = np.zeros((0, 5), dtype=np.float32)
                data_info['ann']['labels_ignore'] = np.array([], dtype=np.int64)
                data_info['ann']['polygons_ignore'] = np.zeros((0, 8), dtype=np.float32)

            data_infos.append(data_info)

        self.img_ids = [*map(lambda x: x['filename'][:-4], data_infos)]
        return data_infos
```

**Comment by Wuwenji18** [comment]
> > 嗨喽，感谢您的回复！ 是否可以理解为数据集的配置，标签就只使用了ir的label，不会使用rgb的label。图片虽然写的是rgb，是在训练过程中也会对应的使用到ir的图像？
> 
> > 
> 
> > 看到论文中，在训练过程是只用了train set，并没有使用 val set。想请问如果在训练过程中使用trainval set去做训练，这样的效果是会更差吗？
> 
> > 
> 
> > 以及现在的配置是使用单卡训练，您有试过多卡训练的一些相关配置参数吗？多卡训练时会什么配置参数比较好呢？
> 
> > 
> 
> > 我想问一下论文是否有做一些公开的演讲或者是论文解读呢？ 万分感谢！
> 
> 
> 
> 我想问一下单卡训练时，单卡的显存最低要求是多少才能运行啊？

我试了，batch为1大概得24G

**Comment by yuanpengwu1** [comment]
> > [#12（评论）](https://github.com/icey-zhang/E2E-MFD/issues/12#issuecomment-2527283160)你可以试试标记我的训练集。希望它能解决你的问题。
> 
> 我尝试了你的训练集，然后遇到了另一个错误：
> 
> 回溯（最近一次调用最后一次）： 文件“/opt/conda/envs/E2E-MFD/lib/python3.9/site-packages/mmcv/utils/registry.py”，第 69 行，在 build_from_cfg 返回 obj_cls（**args） 文件“/root/E2E-MFD/mmrotate/datasets/dronevehicle.py”，第 46 行，在**init** super（DroneVehicleDataset，self）中。**init**（ann_file、pipeline、**kwargs） 文件“/opt/conda/envs/E2E-MFD/lib/python3.9/site-packages/mmdet/datasets/custom.py”，第 97 行，在**init** self.data_infos = self.load_annotations（local_path） 文件“/root/E2E-MFD/mmrotate/datasets/dronevehicle.py”，第 100 行，在 load_annotations 中 difficulty = int（bbox_info[9]） ValueError：以 10 为基数的 int() 的文字无效：'car'
> 
> 在处理上述异常的过程中，又发生了另一个异常：
> 
> 回溯（最近一次调用最后一次）： 文件“/root/E2E-MFD/./tools/train.py”，第 193 行，在 main() 文件“/root/E2E-MFD/./tools/train.py”，第 169 行，在主 数据集中 = [build_dataset（cfg.data.train）] 文件“/root/E2E-MFD/mmrotate/datasets/builder.py”，第 47 行，在 build_dataset 数据集中 = build_from_cfg（cfg，ROTATED_DATASETS，default_args） 文件“/opt/conda/envs/E2E-MFD/lib/python3.9/site-packages/mmcv/utils/registry.py”，第 72 行，在 build_from_cfg 中 引发类型（e）（f'{obj_cls。name **}** : {e}'） ValueError：DroneVehicleDataset：带有基础的 int（）的文字无效10：‘汽车’ 我该如何解决？



> > [#12 (comment)](https://github.com/icey-zhang/E2E-MFD/issues/12#issuecomment-2527283160) You can try labeling my training set. I hope it can solve your problem.
> 
> I try your training set,then I meet another error:
> 
> Traceback (most recent call last): File "/opt/conda/envs/E2E-MFD/lib/python3.9/site-packages/mmcv/utils/registry.py", line 69, in build_from_cfg return obj_cls(**args) File "/root/E2E-MFD/mmrotate/datasets/dronevehicle.py", line 46, in **init** super(DroneVehicleDataset, self).**init**(ann_file, pipeline, **kwargs) File "/opt/conda/envs/E2E-MFD/lib/python3.9/site-packages/mmdet/datasets/custom.py", line 97, in **init** self.data_infos = self.load_annotations(local_path) File "/root/E2E-MFD/mmrotate/datasets/dronevehicle.py", line 100, in load_annotations difficulty = int(bbox_info[9]) ValueError: invalid literal for int() with base 10: 'car'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/root/E2E-MFD/./tools/train.py", line 193, in main() File "/root/E2E-MFD/./tools/train.py", line 169, in main datasets = [build_dataset(cfg.data.train)] File "/root/E2E-MFD/mmrotate/datasets/builder.py", line 47, in build_dataset dataset = build_from_cfg(cfg, ROTATED_DATASETS, default_args) File "/opt/conda/envs/E2E-MFD/lib/python3.9/site-packages/mmcv/utils/registry.py", line 72, in build_from_cfg raise type(e)(f'{obj_cls.**name**}: {e}') ValueError: DroneVehicleDataset: invalid literal for int() with base 10: 'car' how can i solve it?

I also encountered this error, how to solve it

**Comment by yuanpengwu1** [comment]
> > [#12 (comment)](https://github.com/icey-zhang/E2E-MFD/issues/12#issuecomment-2527283160) You can try labeling my training set. I hope it can solve your problem.
> 
> I try your training set,then I meet another error:
> 
> Traceback (most recent call last): File "/opt/conda/envs/E2E-MFD/lib/python3.9/site-packages/mmcv/utils/registry.py", line 69, in build_from_cfg return obj_cls(**args) File "/root/E2E-MFD/mmrotate/datasets/dronevehicle.py", line 46, in **init** super(DroneVehicleDataset, self).**init**(ann_file, pipeline, **kwargs) File "/opt/conda/envs/E2E-MFD/lib/python3.9/site-packages/mmdet/datasets/custom.py", line 97, in **init** self.data_infos = self.load_annotations(local_path) File "/root/E2E-MFD/mmrotate/datasets/dronevehicle.py", line 100, in load_annotations difficulty = int(bbox_info[9]) ValueError: invalid literal for int() with base 10: 'car'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/root/E2E-MFD/./tools/train.py", line 193, in main() File "/root/E2E-MFD/./tools/train.py", line 169, in main datasets = [build_dataset(cfg.data.train)] File "/root/E2E-MFD/mmrotate/datasets/builder.py", line 47, in build_dataset dataset = build_from_cfg(cfg, ROTATED_DATASETS, default_args) File "/opt/conda/envs/E2E-MFD/lib/python3.9/site-packages/mmcv/utils/registry.py", line 72, in build_from_cfg raise type(e)(f'{obj_cls.**name**}: {e}') ValueError: DroneVehicleDataset: invalid literal for int() with base 10: 'car' how can i solve it?

I also encountered this error, how to solve it

**Comment by Nofree-w** [comment]
> > [#12 (comment)](https://github.com/icey-zhang/E2E-MFD/issues/12#issuecomment-2527283160) You can try labeling my training set. I hope it can solve your problem.
> 
> I try your training set,then I meet another error:
> 
> Traceback (most recent call last): File "/opt/conda/envs/E2E-MFD/lib/python3.9/site-packages/mmcv/utils/registry.py", line 69, in build_from_cfg return obj_cls(**args) File "/root/E2E-MFD/mmrotate/datasets/dronevehicle.py", line 46, in **init** super(DroneVehicleDataset, self).**init**(ann_file, pipeline, **kwargs) File "/opt/conda/envs/E2E-MFD/lib/python3.9/site-packages/mmdet/datasets/custom.py", line 97, in **init** self.data_infos = self.load_annotations(local_path) File "/root/E2E-MFD/mmrotate/datasets/dronevehicle.py", line 100, in load_annotations difficulty = int(bbox_info[9]) ValueError: invalid literal for int() with base 10: 'car'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/root/E2E-MFD/./tools/train.py", line 193, in main() File "/root/E2E-MFD/./tools/train.py", line 169, in main datasets = [build_dataset(cfg.data.train)] File "/root/E2E-MFD/mmrotate/datasets/builder.py", line 47, in build_dataset dataset = build_from_cfg(cfg, ROTATED_DATASETS, default_args) File "/opt/conda/envs/E2E-MFD/lib/python3.9/site-packages/mmcv/utils/registry.py", line 72, in build_from_cfg raise type(e)(f'{obj_cls.**name**}: {e}') ValueError: DroneVehicleDataset: invalid literal for int() with base 10: 'car' how can i solve it?

I would like to ask how you solved this problem 'need at least one array to concatenate'

**Comment by Nofree-w** [comment]
> > > > 会不会是因为没有checkpoint='/home/_**/LSK**_/lsk_s_backbone.pth.tar'这个文件报的错呢？看了很多博客都没解决，求助，非常感谢！
> > > 
> > > 
> > > 是的，您需要在lsk_s_fpn_1x_dota_le90.py文件中model.backbone.init_cfg这里传入预训练权重的路径，例如init_cfg=dict(type='Pretrained', checkpoint="/home/.../lsk_s_backbone.pth.tar")
> > 
> > 
> > 我想问一下，lsk_s_backbone.pth.tar这个预训练文件怎么获得？是要找到其中epoch与自己训练时相同的才行吗？谢谢。
> 
> 你可以从这个链接中下载：https://github.com/zcablii/LSKNet 但是我已经在config中加载了权重文件，依然还会报这个错误

我想问问你怎么解决的这个报错，我labels的格式改成了yolo txt，还是一直报这个错，谢谢
